// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY6ndVIikp_vBaKbqFpriwbuFKztNzlME',
    appId: '1:889554647988:web:b46b0ae6f1248f9a2b90e1',
    messagingSenderId: '889554647988',
    projectId: 'elderly-vitals-monitor',
    authDomain: 'elderly-vitals-monitor.firebaseapp.com',
    storageBucket: 'elderly-vitals-monitor.firebasestorage.app',
    measurementId: 'G-L72Y674V8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zZEm7FLLjPqkIuI3lee50TVqwUdMXtU',
    appId: '1:889554647988:android:306fe813bde76d492b90e1',
    messagingSenderId: '889554647988',
    projectId: 'elderly-vitals-monitor',
    storageBucket: 'elderly-vitals-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2-z2WUXBTTT_m8mZnZVn8wfJMycRqvc',
    appId: '1:889554647988:ios:f628667068eba1c52b90e1',
    messagingSenderId: '889554647988',
    projectId: 'elderly-vitals-monitor',
    storageBucket: 'elderly-vitals-monitor.firebasestorage.app',
    iosBundleId: 'com.example.elderlyVitalsMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ2-z2WUXBTTT_m8mZnZVn8wfJMycRqvc',
    appId: '1:889554647988:ios:f628667068eba1c52b90e1',
    messagingSenderId: '889554647988',
    projectId: 'elderly-vitals-monitor',
    storageBucket: 'elderly-vitals-monitor.firebasestorage.app',
    iosBundleId: 'com.example.elderlyVitalsMonitor',
  );
}
